[book]
authors = ["Mohammed Alyousef"]
language = "en"
src = "src"
title = "fltk book"

[rust]
edition = "2021"

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/fltk-rs/fltk-book"
edit-url-template = "https://github.com/fltk-rs/fltk-book/edit/main/{path}"

[output.html.fold]
enable = true
level = 1
